import { createHash, randomUUID } from "node:crypto";
import {
  access,
  mkdir,
  readFile,
  readdir,
  rename,
  rm,
  stat,
  writeFile,
} from "node:fs/promises";
import { dirname, extname, join, relative, resolve } from "node:path";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import { z } from "zod";
import { featureInstrumentationManifestSchema } from "./runtime-contracts.js";

const schemaVersion = 1 as const;
const featureBindingKinds = [
  "server_enforcement",
  "browser_presentation",
  "usage_reporter",
  "funnel_trigger",
  "discovery",
] as const;
export const defaultRoots = ["app", "src", "lib", "components", "pages"];
export const ignoredSegments = new Set([
  ".claude",
  ".git",
  ".next",
  ".output",
  ".turbo",
  "build",
  "coverage",
  "dist",
  "generated",
  "node_modules",
  "playwright-report",
  "public",
  "test-results",
  "vendor",
]);
const supportedExtensions = new Set([
  ".cjs",
  ".js",
  ".jsx",
  ".mjs",
  ".ts",
  ".tsx",
]);
export const sensitivePathPattern = /(^|\/)(\.env|secrets?|credentials?|private[-_.]?keys?)(\.|\/|$)/i;
const generatedMarker = "// Generated by `saasfunnels features setup`. Review before importing.";
const keyPattern = /^[a-z][a-z0-9_.-]{0,79}$/;

const evidenceSchema = z
  .object({
    bindingIdentityFingerprint: z.string().regex(/^[0-9a-f]{64}$/),
    bindingKind: z.enum(featureBindingKinds),
    confidenceBasisPoints: z.number().int().min(0).max(10_000),
    file: z.string().min(1).max(500),
    fingerprint: z.string().regex(/^[0-9a-f]{64}$/),
    line: z.number().int().min(1),
    rationale: z.string().min(1).max(500),
    symbol: z.string().min(1).max(240),
  })
  .strict();

const catalogFeatureSchema = z
  .object({
    accessModel: z.enum(["boolean", "limit"]),
    aliases: z.array(z.string().regex(keyPattern)).max(50),
    description: z.string().max(4_000),
    evidence: z.array(evidenceSchema).max(16),
    key: z.string().regex(keyPattern),
    name: z.string().min(1).max(240),
    unit: z.string().min(1).max(80).nullable(),
  })
  .strict()
  .superRefine((feature, context) => {
    if ((feature.accessModel === "limit") !== Boolean(feature.unit)) {
      context.addIssue({
        code: "custom",
        message: "Only Limit Features declare a unit.",
        path: ["unit"],
      });
    }
  });

export const featureCatalogManifestSchema = z
  .object({
    environment: z.enum(["test", "production"]),
    features: z.array(catalogFeatureSchema).max(5_000),
    generatedBy: z.literal("saasfunnels features setup"),
    schemaVersion: z.literal(schemaVersion),
  })
  .strict()
  .superRefine((manifest, context) => {
    const keys = manifest.features.map((feature) => feature.key);
    if (new Set(keys).size !== keys.length) {
      context.addIssue({
        code: "custom",
        message: "Feature keys must be unique.",
        path: ["features"],
      });
    }
    const identities = manifest.features.flatMap((feature) => [
      feature.key,
      ...feature.aliases,
    ]);
    if (new Set(identities).size !== identities.length) {
      context.addIssue({
        code: "custom",
        message: "Feature keys and aliases cannot overlap.",
        path: ["features"],
      });
    }
  });

export type FeatureCatalogManifest = z.infer<
  typeof featureCatalogManifestSchema
>;

export type FeatureCandidate = {
  accessModel: "boolean" | "limit";
  bindingIdentityFingerprint: string;
  bindingKind: (typeof featureBindingKinds)[number];
  confidenceBasisPoints: number;
  file: string;
  fingerprint: string;
  id: string;
  line: number;
  name: string;
  rationale: string;
  suggestedKey: string;
  symbol: string;
  unit: string | null;
};

export type FeatureSetupEdit = {
  afterHash: string;
  beforeHash: string | null;
  diff: string;
  id: string;
  kind: "generated_constants" | "manifest";
  path: string;
  selected: boolean;
};

export type FeatureSetupInput = {
  accept?: string[];
  accountId?: string;
  apiBaseUrl: string;
  apply: boolean;
  cwd: string;
  environment: "test" | "production";
  exclude?: string[];
  fetch?: typeof fetch;
  include?: string[];
  manifestOnly: boolean;
  mappings?: Record<string, string>;
  prompt?: (message: string) => Promise<string>;
  reject?: string[];
  serverKey?: string;
};

export type FeatureRuntimeCheckResult = {
  decision?: {
    allowed: boolean;
    reasonCode: string;
    source: string;
    value: unknown;
  };
  featureKey?: string;
  reason?: string;
  state: "failed" | "passed" | "skipped";
};

export type FeatureSetupResult = {
  applied: boolean;
  candidates: FeatureCandidate[];
  changeRecordPath?: string;
  edits: FeatureSetupEdit[];
  environment: "test" | "production";
  framework: {
    framework: "nextjs" | "unsupported";
    packageManager: "bun" | "npm" | "pnpm" | "unknown" | "yarn";
    saasFunnelsPackages: string[];
    roots: string[];
  };
  idempotent: boolean;
  instructions: Array<{
    featureKey: string;
    file: string;
    line: number;
    message: string;
    symbol: string;
  }>;
  manifest: FeatureCatalogManifest;
  manifestPath: string;
  ok: boolean;
  reviewUrl: string;
  runtimeCheck: {
    featureKey?: string;
    reason?: string;
    state: "failed" | "passed" | "skipped";
  };
  scannedFileCount: number;
  validation: { errors: string[]; ok: boolean };
};

function sha256(value: string | Buffer) {
  return createHash("sha256").update(value).digest("hex");
}

function stableKey(value: string) {
  const normalized = value
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^[_\d]+|_+$/g, "")
    .slice(0, 80);
  return keyPattern.test(normalized) ? normalized : "feature";
}

function displayName(key: string) {
  return key
    .split(/[_.-]/)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join(" ");
}

function safeRelative(root: string, target: string) {
  const result = relative(root, target).replaceAll("\\", "/");
  return result && !result.startsWith("../") && result !== ".."
    ? result
    : null;
}

async function exists(path: string) {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

function allowedPath(path: string, excludes: string[]) {
  const normalized = path.replaceAll("\\", "/");
  if (sensitivePathPattern.test(normalized)) return false;
  const segments = normalized.split("/");
  if (segments.some((segment) => ignoredSegments.has(segment))) return false;
  return !excludes.some(
    (exclude) =>
      normalized === exclude || normalized.startsWith(`${exclude}/`),
  );
}

async function walkFiles(input: {
  cwd: string;
  excludes: string[];
  roots: string[];
}) {
  const files: string[] = [];
  const queue = input.roots.map((root) => resolve(input.cwd, root));
  while (queue.length && files.length < 500) {
    const current = queue.shift()!;
    const relativePath = safeRelative(input.cwd, current);
    if (!relativePath || !allowedPath(relativePath, input.excludes)) continue;
    let currentStat;
    try {
      currentStat = await stat(current);
    } catch {
      continue;
    }
    if (currentStat.isDirectory()) {
      const entries = await readdir(current, { withFileTypes: true });
      entries
        .sort((left, right) => left.name.localeCompare(right.name))
        .forEach((entry) => queue.push(join(current, entry.name)));
      continue;
    }
    if (
      currentStat.isFile() &&
      currentStat.size <= 256_000 &&
      supportedExtensions.has(extname(current))
    ) {
      files.push(current);
    }
  }
  return files.sort();
}

function nearestSymbol(lines: string[], lineIndex: number) {
  for (let index = lineIndex; index >= Math.max(0, lineIndex - 20); index -= 1) {
    const match = lines[index]?.match(
      /(?:export\s+)?(?:async\s+)?(?:function|class|const|let|var)\s+([A-Za-z_$][\w$]*)/,
    );
    if (match?.[1]) return match[1];
  }
  return "module";
}

function candidatesFromFile(path: string, source: string): FeatureCandidate[] {
  const lines = source.split(/\r?\n/);
  const candidates: FeatureCandidate[] = [];
  const patterns: Array<{
    accessModel: "boolean" | "limit";
    bindingKind: (typeof featureBindingKinds)[number];
    confidenceBasisPoints: number;
    pattern: RegExp;
    rationale: string;
    unit: string | null;
  }> = [
    {
      accessModel: "boolean",
      confidenceBasisPoints: 9_800,
      pattern:
        /(?:hasFeature\s*\(|checkFeature\s*\(|checkEntitlement\s*\(|isFeatureEnabled\s*\()["'`]([a-z][a-z0-9_.-]{1,79})["'`]/g,
      bindingKind: "server_enforcement",
      rationale: "Existing server Feature or entitlement check",
      unit: null,
    },
    {
      accessModel: "boolean",
      bindingKind: "browser_presentation",
      confidenceBasisPoints: 9_600,
      pattern:
        /<FeatureGate[^>]*featureKey\s*=\s*["'`]([a-z][a-z0-9_.-]{1,79})["'`]/g,
      rationale: "Existing browser Feature presentation gate",
      unit: null,
    },
    {
      accessModel: "limit",
      bindingKind: "usage_reporter",
      confidenceBasisPoints: 9_300,
      pattern:
        /(?:usageKey|limitKey|meterKey|featureLimit)\s*[:=]\s*["'`]([a-z][a-z0-9_.-]{1,79})["'`]/g,
      rationale: "Existing usage or limit key",
      unit: "uses",
    },
    {
      accessModel: "boolean",
      bindingKind: "funnel_trigger",
      confidenceBasisPoints: 8_900,
      pattern:
        /(?:deniedFeatureKey|featureDenied|onFeatureDenied)\s*[:=(]\s*["'`]([a-z][a-z0-9_.-]{1,79})["'`]/g,
      rationale: "Denied-access Funnel trigger",
      unit: null,
    },
    {
      accessModel: "boolean",
      bindingKind: "discovery",
      confidenceBasisPoints: 7_600,
      pattern:
        /(?:featureKey\s*[:=]\s*|(?:FEATURES?|ENTITLEMENTS?)\s*(?:=|:)\s*(?:\{|\[)[^\n]*?)["'`]([a-z][a-z0-9_.-]{1,79})["'`]/g,
      rationale: "Feature or entitlement constant",
      unit: null,
    },
  ];
  patterns.forEach((definition) => {
    lines.forEach((line, lineIndex) => {
      definition.pattern.lastIndex = 0;
      let match;
      while ((match = definition.pattern.exec(line))) {
        const key = stableKey(match[1] ?? "");
        const symbol = nearestSymbol(lines, lineIndex);
        const fingerprint = sha256(
          JSON.stringify({
            accessModel: definition.accessModel,
            file: path,
            key,
            line: lineIndex + 1,
            symbol,
          }),
        );
        const bindingIdentityFingerprint = sha256(
          JSON.stringify({
            bindingKind: definition.bindingKind,
            rationale: definition.rationale,
            symbol,
          }),
        );
        candidates.push({
          accessModel: definition.accessModel,
          bindingIdentityFingerprint,
          bindingKind: definition.bindingKind,
          confidenceBasisPoints: definition.confidenceBasisPoints,
          file: path,
          fingerprint,
          id: fingerprint.slice(0, 12),
          line: lineIndex + 1,
          name: displayName(key),
          rationale: definition.rationale,
          suggestedKey: key,
          symbol,
          unit: definition.unit,
        });
      }
    });
  });
  return candidates;
}

async function detectFramework(cwd: string, requestedRoots?: string[]) {
  let packageJson: Record<string, unknown> = {};
  try {
    packageJson = JSON.parse(await readFile(join(cwd, "package.json"), "utf8"));
  } catch {
    // Unsupported projects still receive manifest-only guidance.
  }
  const dependencies = {
    ...(packageJson.dependencies as Record<string, unknown> | undefined),
    ...(packageJson.devDependencies as Record<string, unknown> | undefined),
  };
  const framework =
    typeof dependencies.next === "string" ? ("nextjs" as const) : ("unsupported" as const);
  const packageManager = (await exists(join(cwd, "pnpm-lock.yaml")))
    ? ("pnpm" as const)
    : (await exists(join(cwd, "yarn.lock")))
      ? ("yarn" as const)
      : (await exists(join(cwd, "bun.lockb"))) ||
          (await exists(join(cwd, "bun.lock")))
        ? ("bun" as const)
        : (await exists(join(cwd, "package-lock.json")))
          ? ("npm" as const)
          : ("unknown" as const);
  const roots = (
    requestedRoots?.length ? requestedRoots : defaultRoots
  ).filter((root) => !root.startsWith("../") && !root.startsWith("/"));
  const existingRoots: string[] = [];
  for (const root of roots) {
    if (await exists(resolve(cwd, root))) existingRoots.push(root);
  }
  return {
    framework,
    packageManager,
    saasFunnelsPackages: Object.keys(dependencies)
      .filter((name) => name === "saasfunnels" || name.startsWith("@saasfunnels/"))
      .sort(),
    roots: existingRoots,
  };
}

function manifestFromCandidates(
  environment: "test" | "production",
  candidates: FeatureCandidate[],
  accepted: Set<string>,
  mappings: Record<string, string>,
  existing?: FeatureCatalogManifest | null,
): FeatureCatalogManifest {
  const byKey = new Map<string, FeatureCatalogManifest["features"][number]>(
    (existing?.features ?? []).map((feature) => [
      feature.key,
      {
        ...feature,
        aliases: [...feature.aliases],
        evidence: [...feature.evidence],
      },
    ]),
  );
  candidates
    .filter((candidate) => accepted.has(candidate.id))
    .forEach((candidate) => {
      const key = stableKey(mappings[candidate.id] ?? candidate.suggestedKey);
      const existing = byKey.get(key);
      const evidence = {
        bindingIdentityFingerprint: candidate.bindingIdentityFingerprint,
        bindingKind: candidate.bindingKind,
        confidenceBasisPoints: candidate.confidenceBasisPoints,
        file: candidate.file,
        fingerprint: candidate.fingerprint,
        line: candidate.line,
        rationale: candidate.rationale,
        symbol: candidate.symbol,
      };
      if (existing) {
        if (
          existing.evidence.length < 16 &&
          !existing.evidence.some(
            (item) => item.fingerprint === evidence.fingerprint,
          )
        ) {
          existing.evidence.push(evidence);
        }
        return;
      }
      byKey.set(key, {
        accessModel: candidate.accessModel,
        aliases: [],
        description: "",
        evidence: [evidence],
        key,
        name: displayName(key),
        unit: candidate.accessModel === "limit" ? candidate.unit ?? "uses" : null,
      });
    });
  return featureCatalogManifestSchema.parse({
    environment,
    features: [...byKey.values()].sort((left, right) =>
      left.key.localeCompare(right.key),
    ),
    generatedBy: "saasfunnels features setup",
    schemaVersion,
  });
}

function unifiedDiff(path: string, before: string | null, after: string) {
  if (before === after) return "";
  const beforeLines = before?.split("\n") ?? [];
  const afterLines = after.split("\n");
  return [
    `--- a/${path}`,
    `+++ b/${path}`,
    `@@ -1,${beforeLines.length} +1,${afterLines.length} @@`,
    ...beforeLines.map((line) => `-${line}`),
    ...afterLines.map((line) => `+${line}`),
  ].join("\n");
}

function generatedConstants(manifest: FeatureCatalogManifest) {
  return `${generatedMarker}\n\nexport const saasFunnelsFeatureKeys = ${JSON.stringify(
    Object.fromEntries(
      manifest.features.map((feature) => [
        feature.key.replace(/[^a-zA-Z0-9]+/g, "_").toUpperCase(),
        feature.key,
      ]),
    ),
    null,
    2,
  )} as const;\n\nexport type SaaSFunnelsFeatureKey =\n  (typeof saasFunnelsFeatureKeys)[keyof typeof saasFunnelsFeatureKeys];\n`;
}

async function readable(path: string) {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

type FeatureSetupAtomicIo = {
  mkdir: typeof mkdir;
  read: typeof readable;
  rename: typeof rename;
  remove: typeof rm;
  write: typeof writeFile;
};

export async function applyFeatureSetupChangesAtomically(
  cwd: string,
  changes: Array<{ contents: string; path: string }>,
  io: FeatureSetupAtomicIo = {
    mkdir,
    read: readable,
    remove: rm,
    rename,
    write: writeFile,
  },
) {
  const transactionId = randomUUID();
  const originals = new Map<string, string | null>();
  const staged: Array<{ absolute: string; staged: string }> = [];
  try {
    for (const change of changes) {
      const absolute = resolve(cwd, change.path);
      const relativePath = safeRelative(cwd, absolute);
      if (!relativePath)
        throw new Error(`Refusing to write outside the repository: ${change.path}`);
      await io.mkdir(dirname(absolute), { recursive: true });
      originals.set(absolute, await io.read(absolute));
      const stagedPath = `${absolute}.saasfunnels-${transactionId}.tmp`;
      await io.write(stagedPath, change.contents, { encoding: "utf8", mode: 0o600 });
      staged.push({ absolute, staged: stagedPath });
    }
    for (const entry of staged) await io.rename(entry.staged, entry.absolute);
  } catch (error) {
    for (const entry of staged) await io.remove(entry.staged, { force: true });
    for (const [absolute, contents] of originals) {
      if (contents === null) await io.remove(absolute, { force: true });
      else {
        const restore = `${absolute}.saasfunnels-${transactionId}.restore`;
        await io.write(restore, contents, { encoding: "utf8", mode: 0o600 });
        await io.rename(restore, absolute);
      }
    }
    throw error;
  }
}

export function validateFeatureCatalogManifest(value: unknown) {
  const parsed = featureCatalogManifestSchema.safeParse(value);
  return parsed.success
    ? { errors: [], manifest: parsed.data, ok: true as const }
    : {
        errors: parsed.error.issues.map(
          (issue) => `${issue.path.join(".") || "manifest"}: ${issue.message}`,
        ),
        manifest: null,
        ok: false as const,
      };
}

export async function readFeatureCatalogManifest(path: string) {
  const source = await readFile(path, "utf8");
  return validateFeatureCatalogManifest(parseYaml(source));
}

function record(value: unknown): Record<string, unknown> | null {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : null;
}

export function isFeatureKey(value: string) {
  return keyPattern.test(value);
}

export async function runFeatureRuntimeCheck(input: {
  accountId?: string;
  apiBaseUrl: string;
  featureKey?: string;
  fetch?: typeof fetch;
  serverKey?: string;
}): Promise<FeatureRuntimeCheckResult> {
  if (!input.accountId || !input.featureKey || !input.serverKey) {
    return {
      reason:
        "Set SAASFUNNELS_FUNNELS_SERVER_KEY and provide --account-id and --feature to run the Test decision.",
      state: "skipped" as const,
    };
  }
  const requestId = `feature_check_${sha256(
    `${input.accountId}:${input.featureKey}`,
  ).slice(0, 24)}`;
  try {
    const response = await (input.fetch ?? fetch)(
      `${input.apiBaseUrl}/api/funnels/v1/runtime/entitlements/check`,
      {
        body: JSON.stringify({
          accountId: input.accountId,
          apiVersion: 1,
          environment: "test",
          featureKey: input.featureKey,
          requestId,
        }),
        headers: {
          "content-type": "application/json",
          "x-saasfunnels-api-version": "1",
          "x-saasfunnels-server-key": input.serverKey,
        },
        method: "POST",
      },
    );
    let payload: unknown = null;
    try {
      payload = await response.json();
    } catch {
      // The status still provides a safe, non-secret failure explanation.
    }
    const envelope = record(payload);
    if (!response.ok) {
      const message = record(envelope?.error)?.message;
      return {
        featureKey: input.featureKey,
        reason:
          typeof message === "string"
            ? message
            : `Test entitlement check returned HTTP ${response.status}.`,
        state: "failed",
      };
    }
    const decision = record(record(envelope?.data)?.decision);
    if (
      envelope?.ok !== true ||
      envelope.requestId !== requestId ||
      envelope.apiVersion !== 1 ||
      !decision ||
      decision.featureKey !== input.featureKey ||
      decision.environment !== "test" ||
      typeof decision.allowed !== "boolean" ||
      typeof decision.reasonCode !== "string" ||
      typeof decision.source !== "string"
    ) {
      return {
        featureKey: input.featureKey,
        reason: "The Test entitlement API returned an invalid decision.",
        state: "failed",
      };
    }
    return {
      decision: {
        allowed: decision.allowed,
        reasonCode: decision.reasonCode,
        source: decision.source,
        value: decision.value ?? null,
      },
      featureKey: input.featureKey,
      state: "passed",
    };
  } catch {
    return {
      featureKey: input.featureKey,
      reason: "The Test entitlement API was unavailable.",
      state: "failed" as const,
    };
  }
}

export async function runFeatureSetup(
  input: FeatureSetupInput,
): Promise<FeatureSetupResult> {
  if (input.environment !== "test") {
    throw new Error(
      "Feature setup is Test-only. Review and promote Feature catalogs from Stripe Products.",
    );
  }
  const framework = await detectFramework(input.cwd, input.include);
  if (input.prompt) {
    const confirmation = await input.prompt(
      `Inspect these local roots only: ${framework.roots.join(", ") || "none"}? [y/N] `,
    );
    if (!/^y(?:es)?$/i.test(confirmation.trim())) {
      throw new Error("Feature discovery was cancelled before reading source files.");
    }
  }
  const files = await walkFiles({
    cwd: input.cwd,
    excludes: input.exclude ?? [],
    roots: framework.roots,
  });
  const discovered: FeatureCandidate[] = [];
  let scannedBytes = 0;
  for (const file of files) {
    const source = await readFile(file, "utf8");
    scannedBytes += Buffer.byteLength(source);
    if (scannedBytes > 2_000_000) break;
    const path = safeRelative(input.cwd, file);
    if (!path) continue;
    discovered.push(...candidatesFromFile(path, source));
  }
  const uniqueCandidates = new Map<string, FeatureCandidate>();
  for (const candidate of discovered.sort(
    (left, right) =>
      right.confidenceBasisPoints - left.confidenceBasisPoints ||
      left.file.localeCompare(right.file) ||
      left.line - right.line,
  )) {
    const identity = `${candidate.suggestedKey}:${candidate.accessModel}:${candidate.file}:${candidate.line}`;
    if (!uniqueCandidates.has(identity)) uniqueCandidates.set(identity, candidate);
  }
  const candidates = [...uniqueCandidates.values()].slice(0, 200);
  const manifestPath = ".saasfunnels/catalog.yaml";
  const existingManifestSource = await readable(
    resolve(input.cwd, manifestPath),
  );
  const existingManifestValidation = existingManifestSource
    ? parseFeatureManifestSource(existingManifestSource)
    : null;
  if (existingManifestValidation && !existingManifestValidation.ok) {
    throw new Error(
      `The existing ${manifestPath} is invalid. Run \`saasfunnels catalog validate\` and repair it before setup.`,
    );
  }
  if (
    existingManifestValidation?.manifest &&
    existingManifestValidation.manifest.environment !== input.environment
  ) {
    throw new Error(
      `The existing ${manifestPath} is for ${existingManifestValidation.manifest.environment}; Feature setup only edits the selected ${input.environment} catalog.`,
    );
  }
  const accepted = new Set<string>();
  const accept = new Set(input.accept ?? []);
  const reject = new Set(input.reject ?? []);
  for (const candidate of candidates) {
    if (reject.has(candidate.id) || reject.has(candidate.suggestedKey)) continue;
    if (
      accept.has("all") ||
      accept.has(candidate.id) ||
      accept.has(candidate.suggestedKey)
    ) {
      accepted.add(candidate.id);
      continue;
    }
    if (input.prompt) {
      const answer = await input.prompt(
        `${candidate.suggestedKey} (${candidate.file}:${candidate.line}, ${Math.round(
          candidate.confidenceBasisPoints / 100,
        )}%): accept, reject, or enter a new key? [a/r/key] `,
      );
      if (/^a(?:ccept)?$/i.test(answer.trim())) accepted.add(candidate.id);
      else if (keyPattern.test(answer.trim())) {
        accepted.add(candidate.id);
        input.mappings = { ...(input.mappings ?? {}), [candidate.id]: answer.trim() };
      }
    }
  }
  if (
    input.apply &&
    !input.prompt &&
    candidates.length > 0 &&
    accepted.size === 0 &&
    !existingManifestValidation?.manifest
  ) {
    throw new Error(
      "No discovered Features were approved. Use --accept all or a comma-separated list of candidate IDs/keys before --apply.",
    );
  }
  const manifest = manifestFromCandidates(
    input.environment,
    candidates,
    accepted,
    input.mappings ?? {},
    existingManifestValidation?.manifest,
  );
  const validation = validateFeatureCatalogManifest(manifest);
  const manifestContents = stringifyYaml(manifest, {
    lineWidth: 100,
    sortMapEntries: true,
  });
  const existingManifest = existingManifestSource;
  const constantsPath = ".saasfunnels/features.ts";
  const constantsContents = generatedConstants(manifest);
  const existingConstants = await readable(resolve(input.cwd, constantsPath));
  const constantsSafe =
    existingConstants === null || existingConstants.startsWith(generatedMarker);
  const editInputs = [
    {
      after: manifestContents,
      before: existingManifest,
      id: "manifest",
      kind: "manifest" as const,
      path: manifestPath,
      selected: true,
    },
    ...(!input.manifestOnly && constantsSafe
      ? [
          {
            after: constantsContents,
            before: existingConstants,
            id: "generated_constants",
            kind: "generated_constants" as const,
            path: constantsPath,
            selected: true,
          },
        ]
      : []),
  ];
  const edits = editInputs.map((edit) => ({
    afterHash: sha256(edit.after),
    beforeHash: edit.before === null ? null : sha256(edit.before),
    diff: unifiedDiff(edit.path, edit.before, edit.after),
    id: edit.id,
    kind: edit.kind,
    path: edit.path,
    selected: edit.selected,
  }));
  const changedEdits = edits.filter((edit) => edit.diff);
  let approved = input.apply;
  if (input.prompt && changedEdits.length) {
    const answer = await input.prompt(
      `Apply ${changedEdits.length} reviewed edit${changedEdits.length === 1 ? "" : "s"}? [y/N] `,
    );
    approved = /^y(?:es)?$/i.test(answer.trim());
  }
  let changeRecordPath: string | undefined;
  if (approved && validation.ok && changedEdits.length) {
    const selectedChanges = editInputs.filter((edit) =>
      changedEdits.some((changed) => changed.id === edit.id),
    );
    changeRecordPath = ".saasfunnels/feature-installation.json";
    const record = {
      appliedAt: new Date().toISOString(),
      environment: input.environment,
      files: changedEdits.map((edit) => ({
        afterHash: edit.afterHash,
        beforeHash: edit.beforeHash,
        path: edit.path,
      })),
      schemaVersion,
      transactionId: randomUUID(),
    };
    await applyFeatureSetupChangesAtomically(input.cwd, [
      ...selectedChanges.map((change) => ({
        contents: change.after,
        path: change.path,
      })),
      {
        contents: `${JSON.stringify(record, null, 2)}\n`,
        path: changeRecordPath,
      },
    ]);
  }
  const selectedFeatures = manifest.features.map((feature) => feature.key);
  const check = approved
    ? await runFeatureRuntimeCheck({
        accountId: input.accountId,
        apiBaseUrl: input.apiBaseUrl,
        featureKey: selectedFeatures[0],
        fetch: input.fetch,
        serverKey: input.serverKey,
      })
    : {
        reason: "Apply the reviewed Test manifest before running its entitlement check.",
        state: "skipped" as const,
      };
  const reviewUrl = `${input.apiBaseUrl}/app/settings/integrations/stripe?tab=products&catalog=features&environment=test`;
  const instructions = candidates
    .filter((candidate) => accepted.has(candidate.id))
    .map((candidate) => ({
      featureKey:
        input.mappings?.[candidate.id] ?? candidate.suggestedKey,
      file: candidate.file,
      line: candidate.line,
      message:
        candidate.accessModel === "limit"
          ? `Report absolute ${candidate.unit ?? "usage"} snapshots server-side, then enforce the returned remaining limit before the operation.`
          : "Call the server-side entitlement check before the protected operation; use FeatureGate only for presentation and upsell UI.",
      symbol: candidate.symbol,
    }));
  if (!constantsSafe) {
    instructions.unshift({
      featureKey: "catalog",
      file: constantsPath,
      line: 1,
      message:
        "The existing file is not SaaSFunnels-generated, so it was left byte-for-byte unchanged. Import canonical keys manually or move the file before applying.",
      symbol: "module",
    });
  }
  return {
    applied: Boolean(approved && validation.ok && changedEdits.length),
    candidates,
    ...(changeRecordPath ? { changeRecordPath } : {}),
    edits,
    environment: input.environment,
    framework,
    idempotent: changedEdits.length === 0,
    instructions,
    manifest,
    manifestPath,
    ok: validation.ok,
    reviewUrl,
    runtimeCheck: check,
    scannedFileCount: files.length,
    validation: { errors: validation.errors, ok: validation.ok },
  };
}

export function parseFeatureMappings(values: string[]) {
  return Object.fromEntries(
    values.flatMap((value) => {
      const separator = value.indexOf("=");
      if (separator <= 0) return [];
      const candidate = value.slice(0, separator).trim();
      const key = value.slice(separator + 1).trim();
      return candidate && keyPattern.test(key) ? [[candidate, key]] : [];
    }),
  );
}

export function parseFeatureManifestSource(source: string) {
  return validateFeatureCatalogManifest(parseYaml(source));
}

export function buildFeatureInstrumentationHandoff(input: {
  discoveryRoots?: readonly string[];
  manifest: FeatureCatalogManifest;
  producer?: "cli" | "github_action" | "github_app";
  repositoryKey: string;
  repositoryRevision: string;
  scanRole?: "series" | "candidate";
  sdkVersions?: readonly string[];
  validatedAt?: string;
}) {
  const manifestFingerprint = sha256(JSON.stringify(input.manifest));
  return featureInstrumentationManifestSchema.parse({
    bindings: input.manifest.features.flatMap((feature) =>
      feature.evidence.map((evidence) => ({
        bindingIdentityFingerprint: evidence.bindingIdentityFingerprint,
        bindingKind: evidence.bindingKind,
        evidenceFingerprint: evidence.fingerprint,
        featureKey: feature.key,
        line: evidence.line,
        repositoryPath: evidence.file,
        symbol: evidence.symbol,
      })),
    ),
    discoveryRoots: [...new Set(input.discoveryRoots ?? [])].sort(),
    environment: input.manifest.environment,
    manifestFingerprint,
    manifestVersion: manifestFingerprint.slice(0, 16),
    producer: input.producer ?? "cli",
    repositoryKey: input.repositoryKey,
    repositoryRevision: input.repositoryRevision,
    scanRole: input.scanRole ?? "series",
    schemaVersion: 2,
    sdkVersions: [...new Set(input.sdkVersions ?? [])].sort(),
    validatedAt: input.validatedAt ?? new Date().toISOString(),
    validationState: "valid",
  });
}

export function featureSdkVersionsFromPackageJson(value: unknown) {
  if (!value || typeof value !== "object" || Array.isArray(value)) return [];
  const packageJson = value as Record<string, unknown>;
  const dependencies = {
    ...(packageJson.dependencies as Record<string, unknown> | undefined),
    ...(packageJson.devDependencies as Record<string, unknown> | undefined),
  };
  const packageNames = [
    "@saasfunnels/funnels-browser",
    "@saasfunnels/funnels-react",
  ];
  return packageNames.flatMap((name) => {
    const declared = dependencies[name];
    if (typeof declared !== "string") return [];
    const match = declared.match(/(?:^|[^\d])(\d+\.\d+\.\d+)(?:$|[^\d])/);
    return match?.[1] ? [match[1]] : [];
  });
}

export function featureSetupSummary(result: FeatureSetupResult) {
  return [
    `Framework: ${result.framework.framework} · ${result.framework.packageManager}`,
    `Scope: ${result.framework.roots.join(", ") || "no supported roots"}`,
    `Candidates: ${result.candidates.length}`,
    `Features selected: ${result.manifest.features.length}`,
    ...result.edits.flatMap((edit) =>
      edit.diff ? [`\n${edit.diff}`] : [`Unchanged: ${edit.path}`],
    ),
    result.applied
      ? `\nApplied reviewed edits. Change record: ${result.changeRecordPath}`
      : result.idempotent
        ? "\nNo duplicate instrumentation was added; the generated files are current."
        : "\nDry run only. Re-run with --apply after reviewing the complete diff.",
    `Runtime check: ${result.runtimeCheck.state}${result.runtimeCheck.reason ? ` · ${result.runtimeCheck.reason}` : ""}`,
    `Review Features: ${result.reviewUrl}`,
  ].join("\n");
}
